"""add chat session and message tables

Revision ID: 2f4b9c1d7a3e
Revises: 13d2068684ab
Create Date: 2026-01-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added
from app.schemas.chat_schema import ChatRoleEnum

# ci: trigger migration checks


# revision identifiers, used by Alembic.
revision = "2f4b9c1d7a3e"
down_revision = "13d2068684ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ChatSession",
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ChatSession_id"), "ChatSession", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ChatSession_user_id"),
        "ChatSession",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "ChatMessage",
        sa.Column("session_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "role", sqlalchemy_utils.types.choice.ChoiceType(ChatRoleEnum), nullable=False
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["ChatSession.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ChatMessage_id"), "ChatMessage", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ChatMessage_session_id"),
        "ChatMessage",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ChatMessage_session_id"), table_name="ChatMessage")
    op.drop_index(op.f("ix_ChatMessage_id"), table_name="ChatMessage")
    op.drop_table("ChatMessage")
    op.drop_index(op.f("ix_ChatSession_user_id"), table_name="ChatSession")
    op.drop_index(op.f("ix_ChatSession_id"), table_name="ChatSession")
    op.drop_table("ChatSession")
    # ### end Alembic commands ###
